services:
  bot:
    build: .
    ports:
      - "7000:7000"
    environment:
      BOT_TOKEN: "$bot_token"
      OWNER: "${owner_id:-212591138945630213}"
      DB_URL: "jdbc:postgresql://${DOCKER_GATEWAY_HOST:-host.docker.internal}:$db_port/$db_db"
      DB_USER: "$db_user"
      DB_PW: "$db_pw"
      GK_ENABLED: "$gk_enabled"